config/routes.rb
MongoidApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:omniauth_callbacks => 'authentications', :registrations => 'registrations'}

  resources :articles do
    resources :comments
  end
 resources :comments do
    resources :comments
  end

  root :to => 'articles#index'

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :content, :type => String

  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  has_many :comments, :as => :commentable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_filter :get_parent
 
  def new
    @comment = @parent.comments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end


  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = @parent.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        current_user.comments << @comment if current_user
        format.html { redirect_to root_url, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to root_url, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
private
  def get_parent
    @parent = Article.find(params[:article_id]) if params[:article_id]
    @parent = Comment.find(params[:comment_id]) if params[:comment_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.haml
%li  
  -if comment.user
    %p= comment.user.email
  -else
    %p 
      Anonymous
  %p= comment.content
  =link_to "Edit", edit_comment_path(comment)
  \|
  =link_to "Delete", comment, :method => :delete
  \|
  =link_to "Add reply", new_comment_comment_path(comment)
  %ul
    =render :partial => "comments/comment", :collection => comment.comments

app/views/comments/_form.html.haml
= form_for [@parent, @comment] do |f|
  -if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th Content
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.content
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @comment.content

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path