config/routes.rb
MongoidApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:omniauth_callbacks => 'authentications', :registrations => 'registrations'}

  resources :articles do
    resources :comments
  end
 resources :comments do
    resources :comments
  end

  root :to => 'articles#index'

end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, :type => String
  field :body, :type => String

  belongs_to :user
  has_many :comments, :as => :commentable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
  end


  def create
    respond_to do |format|
      if @article.save
        current_user.articles << @article if current_user
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  -if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
- @articles.each do |article|
    %h3= link_to article.title, article_path(article)
    %span#dop
        published
        = article.user.name ? article.user.name : article.user.email 
    %p= article.body
    %p 
        = link_to 'Edit', edit_article_path(article)
        \|
        = link_to 'Delete', @article, :method => :delete
        \|        
        =link_to "comments:", article_path(article)
        =article.comments.size

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Body:
  = @article.body
-if @article.user
  %p
    %b author:
    = @article.user.email
-else
  %p
    Anonymous
= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Delete', @article, :method => :delete
\|
= link_to 'Add comment', new_article_comment_path(@article)
%br
%ul
  =render :partial => "comments/comment", :collection => @article.comments