config/routes.rb
MongoidApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => {:omniauth_callbacks => 'authentications', :registrations => 'registrations'}

  resources :articles do
    resources :comments
  end
 resources :comments do
    resources :comments
  end

  root :to => 'articles#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoidApp</title>
  <%= stylesheet_link_tag    "layout" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 
</head>
<body>
  <div id = "menu">
    <% unless current_user%>
      <span id = "regs">
        <%= link_to "sign in", new_user_session_path %> or
        <%= link_to "sign up", new_user_registration_path %>
      </span>
    <% else %>
      <span id = "regs">
        Hello <%= current_user.name ? current_user.name : current_user.email %>!   
        <%= link_to "sign out", destroy_user_session_path, :method => :delete %>
      </span> 
      <span id = "regs"> you are <%= current_user.role.humanize %></span>

      <span id = "regs" style = "margin-left: 100px;"> 
          <% if session[:provider] %>
            loged by <%= session[:provider] %>
          <%end%>
      </span>
    <% end %>
     <span id = "links">
        <%= link_to image_tag("vk.png", :size => "25x25"), user_omniauth_authorize_path(:vkontakte) %> 
        <%= link_to image_tag("facebook.png", :size => "25x25"), user_omniauth_authorize_path(:facebook) %>    
        <%= link_to image_tag("twitter.png", :size => "25x25"), user_omniauth_authorize_path(:twitter) %> 
      </span>  
  </div>  
  <div id = "content-menu">
    <%= link_to "Create article", new_article_url %>
  </div>   
  <div id = "content">
      <%= yield %>
  </div>
</body>
</html>